### ISSUE TITLE
Restart stream when browser back in focus

### ISSUE THREAD

**Issue by Tnuz** [deepch/RTSPtoWebRTC#102]
When a client minimizes the browser or switches to a different tab, the video stops.
This message appears:
`Client Not Send ACK (probably the browser is minimized) or tab not active Close client`

To restart the stream, the page needs to refreshed/reloaded.

Would it be possible to make the stream go again automatically when the  web page/tab is back in focus?
Or maybe an option to have it running in the background at all times?

I'm thinking something that will be handled on the client side (javascript) or on the server side (config.json)

**Comment by yeshivsher** [comment]
Hi, did you find a way to solve it?

**Comment by Tnuz** [comment]
Seems to be solves in a later release. It's working for me now.
