### ISSUE TITLE
Publish releases and docker images

### ISSUE THREAD

**Issue by allenporter** [deepch/RTSPtoWebRTC#127]
I'm working on taking the RTSPtoWebRTC Home Assistant custom component based on https://github.com/AlexxIT/WebRTC and making it into an official home assistant add-on. This would involve things like publishing a docker image, and I thought it might make sense to have that live in this project so everyone can benefit rather than creating additional images off to the side.

I was imagining this project could:
- Have a github based action that [publishes docker images](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images)
- Occasionally tag releases/changelog as significant updates land

If it is agreed this is worthwhile, I can help set it up.

**Comment by allenporter** [comment]
I've sent PR https://github.com/deepch/RTSPtoWebRTC/pull/133 as a next step in the conversation to see if you're interested in doing this.

**Comment by allenporter** [comment]
Thanks for merging. Are you up for making a release on docker hub? My impression is we'll want you to do this as repository owner as described in #133

**Comment by deepch** [comment]
Thanks for pull. I have problems with time right now. 
Maybe I can connect you to a project on this task?

**Comment by Arno0x** [comment]
Hi,

Is there any binary release for ARM arch (Raspberry Pi) available ?

Thx.

**Comment by allenporter** [comment]
A couple things from my side:
- I'm personally still kind of new to how docker golang releases are managed across architectures and was looking into how to do that, but didn't see a simple recipe.
- It seemed like the existing `Dockerfile` in the repo doesn't specify an architecture.
- There are no official images/releases for this repo yet anywhere as far as I am aware
- I'm personally now spending more time looking at `RTSPtoWeb` instead as discussed in the PR thread -- since it has many more features and functionality than this service -- so I probably won't be looking into this for this project.
