### ISSUE TITLE
ReferenceError: startSession is not defined

### ISSUE THREAD

**Issue by abdullokh-mukhammadjonov** [deepch/RTSPtoWebRTC#129]
I cloned the repo and followed the instruction on the project's homepage. Streaming does not start. On the browser console I see ```ReferenceError: startSession is not defined```. I believe ```startSession``` is fired when the 'start session' button is clicked. I could not fine ```startSession``` in any .js files either

**Comment by vdalex25** [comment]
I removed the button - it remains from the old version
the stream should start automatically when the page is loaded, if this does not happen then check the stream itself, it may not work

**Comment by abdullokh-mukhammadjonov** [comment]
Thanks. Error is gone
