### ISSUE TITLE
.\main.go:17:5: undefined: StartHTTPServer

### ISSUE THREAD

**Issue by careylipu** [deepch/RTSPtoWebRTC#13]
Can you help me build it or relase a config able exe?
# command-line-arguments
.\main.go:17:5: undefined: StartHTTPServer
.\main.go:32:6: undefined: videoTrack
.\main.go:33:4: undefined: videoTrack

![图片](https://user-images.githubusercontent.com/15045646/66981037-38a49d00-f0e5-11e9-8837-c289bf3a293e.png)

**Comment by deepch** [comment]
I will fix it after the weekend.
