### ISSUE TITLE
Only works on same network ?.

### ISSUE THREAD

**Issue by anand-010** [deepch/RTSPtoWebRTC#137]
I have a made a plugin like websocket based signaling server and it works when both devices on the same wifi network.
If i tried to connect through other network it's not working.

I have confirmed that initial codec and sdp transferring is working.
What went wrong here.
I am used my mobile data on the second device.

**Comment by anand-010** [comment]
ionic app that i have made.
1. On same network.
![WhatsApp Image 2022-01-10 at 8 51 10 AM (1)](https://user-images.githubusercontent.com/32414977/148714906-0d44318d-80c0-4f1a-bcc6-da2a5fa726d5.jpeg)
2. On mobile data.
![WhatsApp Image 2022-01-10 at 8 51 10 AM](https://user-images.githubusercontent.com/32414977/148714923-a41646fd-495a-498f-bcfb-68acfc505690.jpeg)

**Comment by anand-010** [comment]
I have also tried with local tunneling.
same result.
It only works locally.
![WhatsApp Image 2022-01-10 at 10 55 25 AM](https://user-images.githubusercontent.com/32414977/148721760-4d4325ca-8d6e-46ab-942e-efa47682228a.jpeg)

**Comment by anand-010** [comment]
I am closing this issue and creating new one.

**Comment by mnuriyumusak** [comment]
any solution?

**Comment by anand-010** [comment]
No.
This project only concentrated on playing live videos on webpage.
UDP puch hole is not part of this project.
I've spend a lot of time by assuming webrtc is always udp punch hole based.

**Comment by allenporter** [comment]
You can use a stun server -- requires configuring the server and player, thought here isn't a recipe. Some discussion in https://github.com/deepch/RTSPtoWeb/issues/138
