### ISSUE TITLE
Should this work with the server behind a NAT?

### ISSUE THREAD

**Issue by trankin** [deepch/RTSPtoWebRTC#148]
RTSPtoWebRTC is working flawlessly for me when on a local network, but I cannot get it to work as expected when the viewer is on another network.  

I'm under the impression that the STUN servers should help both sides navigate the NAT and establish a connection.

I've exposed the RTSPtoWebRTC HTTP port via ngrok to reverse proxy to the server, the client does get signaling information just fine, but fails to actually connect.

I can do other WebRTC tests just fine from the same computer that is running RTSPtoWebRTC, but with the built in camera, and they work just fine.  There may be (likely are) some complexities with with establishing the peer to peer connection that I don't understand, but this case that I'm exploring is one that I perceive should generally be possible, and my understanding is that a TURN server is needed for some rarer edge cases.

client browser -> firewall/router (nat) -> internet <- firewall/router (nat) (port forwarding 8083) <- server (RTSPToWebRTC) <- IP Camera
^^ not working, I get signaling info, but the data stream does not connect.

My overall goal is the above setup, but without port forwarding the signaling port and using something like mqtt to kick off the nat traversal.

Any insight would be appreciated.. note that I ran this same scenario with RTSPtoWeb with precisely the same results.

**Comment by therealhalifax** [comment]
I have the same issue. with the new HA integration. Interesting; with the RTSP streams directly from the camera its working via the WebRTC Camera custom inegration. @allenporter So I am not sure that its only caused by network setup.

**Comment by chriswiggins** [comment]
The issue here is that the server is not using STUN to discover the external-ip of the RTSPtoWebRTC server - so your browser is only getting local candidates.

This might be the way that the integration with Pion is occurring. I develop with WebRTC daily so will look into whether or not this is an easy fix 👍

**Comment by chriswiggins** [comment]
Hang on a tick, I've just found that this is supported via config, but HomeAssistant doesn't allow us to set those variables. Will look into adding a PR upstream to sort

**Comment by jonas893** [comment]
@chriswiggins Have you found a solution with the server STUN? For me, the video stream also works only locally.

**Comment by chriswiggins** [comment]
This repo supports STUN servers, but for whatever reason the WebRTC player in HomeAssistant doesn't. That'll need fixing so will find the source and open a PR

**Comment by trankin** [comment]
@chriswiggins , looking forward to seeing what you find.   Do you mind providing the information that you found re: the server getting it's external IP address from STUN?   I've configured STUN servers on both the client and server, and I made a quick signaling service to allow an external client to initiate the connection through the firewalls.. but I never get a connection.    

Just makes me think that maybe I've configured the server incorrectly.. or that the server is not getting an external IP regardless of the configuration of the STUN servers..   though I may have missed something documented.

NOTE, that my use case is not with Home Assistant, but using the built in example client and server... and a slightly modified signaling layer that bypasses the need to communicate directly with the server over HTTP..

Regards,

Thomas

**Comment by trankin** [comment]
https://github.com/deepch/RTSPtoWeb/issues/138
