### ISSUE TITLE
HA Add-on not using http_port config change

### ISSUE THREAD

**Issue by terryhonn** [deepch/RTSPtoWebRTC#153]
I'm using the Home Assistant add-on, and need to have the RTSPtoWebRTC server serve http via a different port. I've tried:

```
 streams:
  - name: South Shop
    url: rtsp://192.168.1.109:8554/south-shop-cam
  - name: Demo_H264_AAC
    url: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
server:
  - http_port: ':8084'
```
but the logs indicate it's still serving on 8083:

```
[GIN-debug] Listening and serving HTTP on :8083
[GIN-debug] [ERROR] listen tcp :8083: bind: address already in use
2022/03/03 15:30:27 Start HTTP Server error listen tcp :8083: bind: address already in use
```

Am I just not putting the param in configuration correctly? Thanks!

**Comment by allenporter** [comment]
Can you file this at https://github.com/allenporter/stream-addons/issues since this is about the home assistant add on itself?
