### ISSUE TITLE
Chrome Android/IOS issue

### ISSUE THREAD

**Issue by ccko** [deepch/RTSPtoWebRTC#16]
Hi
Chrome on android and ios cannot see video.
It's keep loading.

Thanks.

**Comment by deepch** [comment]
chrome version?

**Comment by deepch** [comment]
you can see support table

https://caniuse.com/#search=webrtc

**Comment by chi-chung-ko** [comment]
android chrome version is 80.0.3987.87
ios chrome version is  79.0.3945.73

**Comment by jp555soul** [comment]
@chi-chung-ko I'm getting the same error.

**Comment by Emalton** [comment]
Chrome for Windows doesn't work either
![image](https://user-images.githubusercontent.com/9328458/79595650-daad3e00-80a4-11ea-9228-db33ee011b05.png)

**Comment by deepch** [comment]
I will check it next week.

**Comment by deepch** [comment]
im update module, and check on Mac OS Chrome 81.0.4044.113 no problem it work.
I check on windows on next weak.

**Comment by cedricve** [comment]
Have the same issue on Chrome OSX. It shows the error message, but afterwards it shows the stream correctly.

**Comment by deepch** [comment]
I'm check it

**Comment by deepch** [comment]
You can check new version, Firefox, Safari support added.
I check rtsp://184.80.5.148:554/axis-media/media.amp?videocodec=h264 work local perfect.

**Comment by deepch** [comment]
![Снимок экрана 2020-05-08 в 18 33 18](https://user-images.githubusercontent.com/7899955/81421685-843e9700-915a-11ea-997b-6ac65c08b135.png)

I and Ditri fixed some of the problems today.

work on Mac OS =  chrome, safari, firefox
work on IOS = safari (need fix ack)

**Comment by cedricve** [comment]
cool will test it out
