### ISSUE TITLE
Google browser access address 127.0.0.1:8083, loading video is very slow, about 10 seconds?

### ISSUE THREAD

**Issue by woshiwoyali** [deepch/RTSPtoWebRTC#17]
Hello, I ran the project go run. / *. Go, and then I used Google browser to visit the address 127.0.0.1:8083. I found that the video loading was very slow, which took about 10 seconds. How can I adjust this to shorten the time of loading video.

**Comment by deepch** [comment]
video wait key frame try change iframe interval

**Comment by doudoubean** [comment]
where can I find iframe interval？
