### ISSUE TITLE
WritePacket WebRTC Client Offline

### ISSUE THREAD

**Issue by 183demao** [deepch/RTSPtoWebRTC#183]
Hello, this is the situation. I set up a service on one machine, the access on the machine is normal, and another computer in the local area network accesses the web page normally, when the video stream is loaded, it prompts to close the connection (disconnected), I make sure that the port number is not disabled (8083) ), the firewalls are turned off on both machines, is there any way to check the detailed error, or have you ever encountered this situation?

![1659072571602](https://user-images.githubusercontent.com/16781295/181689238-69003169-f38d-4a2c-a6b1-73a1c46a6425.jpg)
![微信截图_20220729133015](https://user-images.githubusercontent.com/16781295/181689291-8404c672-44c1-4ee4-93c1-d23bae7a0e96.png)

**Comment by Cacsjep** [comment]
What shows the webrtc internals about the ICE connection when using Chrome ?

**Comment by yanhua1012** [comment]
I have the same probloem. there are icecandidat error from chrome as follows: 
url: stun:stun.l.google.com:19302
address: [0:0:0:x:x:x:x:x]
port: 57003
host_candidate: [0:0:0:x:x:x:x:x]:57003
error_text: STUN host lookup received error.
error_code: 701

Is there any requirement for using  stu server of google? 

![image](https://user-images.githubusercontent.com/17564030/187026647-e2ab69ce-29d5-42ea-bf71-8d53754bcdac.png)
![image](https://user-images.githubusercontent.com/17564030/187026626-77dd41ca-c4f2-46aa-98b1-46dfce188a5f.png)
![image](https://user-images.githubusercontent.com/17564030/187026709-6682ff71-380d-4f52-8d16-947a7bb32cbd.png)
![image](https://user-images.githubusercontent.com/17564030/187026878-42a6b112-fe7a-4a26-96fd-4c6e96ed17bb.png)

**Comment by acschristoph** [comment]
Just for testing remove ICE Servers from conf and remove also there the ice server. Also u can try other ICE Servers, there is No requirement to use the Google stun

**Comment by yanhua1012** [comment]
Originally I started RTSPtoWebRTC Service in docker container.
After Starting it in my real computer, It works.
Maybe there are some connections issue betwwen google stun and docker container.

**Comment by acschristoph** [comment]
OK Look you can Google the Error Code 701, it looks like ether the Server or client dont can reach the stun Server. You should check from your docker container If the used ports for stun Server reachable.

**Comment by allenporter** [comment]
Try using host network if you aren't already
