### ISSUE TITLE
How to record video?

### ISSUE THREAD

**Issue by 18251968697** [deepch/RTSPtoWebRTC#24]
Emmmmm....

**Comment by deepch** [comment]
Easy record to file format 

crate file test.h264

00 00 00 01 SPS 00 00 00 01 PPS 00 00 00 01 Key Frame 00 00 00 01  Not Key Frame
and etc....

ffplay test.h264

**Comment by 18251968697** [comment]
> Easy record to file format
> 
> crate file test.h264
> 
> 00 00 00 01 SPS 00 00 00 01 PPS 00 00 00 01 Key Frame 00 00 00 01 Not Key Frame
> and etc....
> 
> ffplay test.h264

But how to create file test.h264?I'm not good at golang :(
