### ISSUE TITLE
Help to understand code flow

### ISSUE THREAD

**Issue by PushkarDureja** [deepch/RTSPtoWebRTC#27]
I want to implement WebRTC streaming in js but its difficult for me to understand the code flow in go . Can you guide me through it or provide a link which could help to implement it in js?

**Comment by vdalex25** [comment]
https://www.webrtc-experiment.com/ - maybe this link can help you, but WebRTC currently has very poor cross-browser compatibility. For example, it’s very difficult to establish a connection between Opera and Firefox.
