### ISSUE TITLE
demo1 rtsp: codec data change, please call HandleCodecDataChange() 

### ISSUE THREAD

**Issue by aronsong** [deepch/RTSPtoWebRTC#28]
detailed log

OPTIONS rtsp://192.168.1.100:554/test RTSP/1.0
CSeq: 1

DESCRIBE rtsp://192.168.1.100:554/test RTSP/1.0
CSeq: 2
Accept: application/sdp

< v=0
o=- 0 0 IN IP4 127.0.0.1
s=Media Presentation
c=IN IP4 192.168.1.100
t=0 0
a=tool:libavformat 58.46.101
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z0LglageAIn5UA==,aM4wpIA=; profile-level-id=42E095
a=control:streamid=0

SETUP rtsp://192.168.1.100:554/test/streamid=0 RTSP/1.0
CSeq: 3
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
Session: cAa2lnZMg

PLAY rtsp://192.168.1.100:554/test RTSP/1.0
CSeq: 4
Session: cAa2lnZMg
2020/06/18 14:34:54 demo1 rtsp: codec data change, please call HandleCodecDataChange()
2020/06/18 14:34:54 demo1 reconnect wait 5s
2020/06/18 14:34:59 demo1 connect rtsp://192.168.1.100/test

**Comment by deepch** [comment]
please share you stream I test it.

**Comment by aronsong** [comment]
> please share you stream I test it.

There are two sources of rtsp streaming
1.ip camera.
2. Use ffmpeg to push the mp4 file to the rtsp stream output by easyDarwin.
There are problems with the above two methods

**Comment by aronsong** [comment]
> > please share you stream I test it.
> 
> There are two sources of rtsp streaming
> 
> 1. The rtsp stream provided by the ip camera.
> 2. Use ffmpeg to get the rtsp stream of the ip camera and forward it to the easyDarwin streaming server.
>    There are problems with the above two methods

However, using ffmpeg to read mp4 files and turn them into rtsp streams and push them to the easyDarwin streaming server can be played.

**Comment by deepch** [comment]
Good day.

We are working on a new version of the rtsp client.

**Comment by deepch** [comment]
Try it in the new version there pion v3 was updated and rtsp v2 client was updated
