### ISSUE TITLE
i frame 

### ISSUE THREAD

**Issue by buzai** [deepch/RTSPtoWebRTC#30]
rtsp flower screen, view have half green, but this stream is OK in vlc. I think it not from i frame decoding leads to some information loss. Is there a way to discard some frames until I get the i frame?

**Comment by deepch** [comment]
Good day.

We are working on a new version of the rtsp client. But in order to recreate your problem we need to access your rtsp stream.

**Comment by deepch** [comment]
Try it in the new version there pion v3 was updated and rtsp v2 client was updated
