### ISSUE TITLE
Not working in Chrome or Edge

### ISSUE THREAD

**Issue by oneduality** [deepch/RTSPtoWebRTC#33]
It works in Firefox but not Chrome or Edge ( Windows 10 ) 

Also.. is there any way to change the layout to show previews or anything? or to stream all as mini streams and click to expand?

I'm wanting to use this for a security camera interface, switching back and forth is very inconvenient for that.. just asking.. but if there's no solution for Chrome I may have to keep looking for something else.. :( which would suck because this is the closest I've gotten to getting something to work properly.

Errors I'm getting:

Uncaught (in promise) DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. a=ssrc:4195826001 msid:Channel 1_pion video Expected format "msid:<identifier>[ <appdata>]".

Uncaught ReferenceError: startSession is not defined at HTMLButtonElement.onclick (Channel 1:39)

It also doesn't work on mobile safari ( iPhone )

**Comment by deepch** [comment]
Good day.

I will try to repeat the problem.
If you are using an IP camera, I recommend using another solution. https://github.com/deepch/RTSPtoWSMP4f
