### ISSUE TITLE
Stream not playing

### ISSUE THREAD

**Issue by heinrichwinter** [deepch/RTSPtoWebRTC#34]
![Screenshot (29)](https://user-images.githubusercontent.com/51024660/88517115-a673e280-cfee-11ea-924b-2ee29f441baa.png)
![Screenshot (29)](https://user-images.githubusercontent.com/51024660/88517441-1f733a00-cfef-11ea-8d1a-7aba8f6e97f3.png)
![Screenshot (30)](https://user-images.githubusercontent.com/51024660/88517449-21d59400-cfef-11ea-9488-4904b769698f.png)
![Screenshot (31)](https://user-images.githubusercontent.com/51024660/88517456-2306c100-cfef-11ea-9ecb-2afc8b9d19c7.png)

Hi, 
The stream is not playing in the browser, it checks the connection state and also that the track is delivered and then it says connected but there is no stream playing. Can you please help me! Please find my outputs attached 
Thank you

**Comment by lianmafutra** [comment]
how it work ?
