### ISSUE TITLE
Write codec info error nil

### ISSUE THREAD

**Issue by heinrichwinter** [deepch/RTSPtoWebRTC#35]
I receive this error when trying to play the stream, can you please help or provide some guidance ?

**Comment by deepch** [comment]
Good day.

We are working on a new version of the rtsp client. But in order to recreate your problem we need to access your rtsp stream.

**Comment by heinrichwinter** [comment]
Can i give you the stream privately ?

**Comment by deepch** [comment]
I recommend waiting for next week for a new version to be released.

**Comment by heinrichwinter** [comment]
Okay awesome thank you

**Comment by martinkouba** [comment]
i have the same issue. my rtsp stream does not have audio. can it have to do with that?

**Comment by thsshz** [comment]
Is there any update about this problem?

**Comment by anandeshwar** [comment]
I have the same issue when connecting to stream from the Web, it display "Write Codec Info error <nil", i can share my RTSP Stream .Please let me know. Thank you

**Comment by deepch** [comment]
Try it in the new version there pion v3 was updated and rtsp v2 client was updated

**Comment by anandeshwar** [comment]
Thank you, i will try it..
