### ISSUE TITLE
Compability issue: "Video might not work with codec 102"- Hikvision camera unit 

### ISSUE THREAD

**Issue by viljo** [deepch/RTSPtoWebRTC#37]
When I run the code together with my hikvision camera stream/record unit I get the following log:

[GIN] 2020/08/07 - 11:58:10 | 200 |     291.505µs |   94.254.117.91 | GET      "/player/demo1"
[GIN] 2020/08/07 - 11:58:10 | 200 |      99.604µs |   94.254.117.91 | GET      "/static/js/app.js?ver=2020-08-07%2011%3a58%3a10.432590088%20%2b0000%20UTC%20m%3d%2b91.940309803"
2020/08/07 11:58:10 Write Codec Info error <nil>
[GIN] 2020/08/07 - 11:58:10 | 200 |      76.524µs |   94.254.117.91 | GET      "/codec/demo1"
2020/08/07 11:58:10 Request demo1
2020/08/07 11:58:10 Video might not work with codec 102
2020/08/07 11:58:10 Work payloadType 102
[GIN] 2020/08/07 - 11:58:10 | 200 |    20.06585ms |   94.254.117.91 | POST     "/recive"
2020/08/07 11:58:20 Connection State has changed failed
2020/08/07 11:58:20 Client Close Exit
2020/08/07 11:58:20 Connection State has changed closed
2020/08/07 11:58:20 Client Close Exit

**Comment by yeshivsher** [comment]
Did you solve it?

**Comment by viljo** [comment]
Nope. I ended up not using WebRTC encoding.

**Comment by yeshivsher** [comment]
Can you share the alternative?

**Comment by deepch** [comment]
Try it in the new version there pion v3 was updated and rtsp v2 client was updated
