### ISSUE TITLE
Force relay mode on WebRTC/ICE transmission

### ISSUE THREAD

**Issue by HyperDenton** [deepch/RTSPtoWebRTC#39]
Hi, I'm trying to deploy this project on my server, but I couldn't play it without VPN since WebRTC (or ICE protocol) picks a **random port** for transmission which my firewall blocked. Is it possible to enforce relay mode on ICE transmission so that I can fix the port for later firewall permission?

**Comment by deepch** [comment]
This example uses pion you better ask them this question https://github.com/pion/webrtc

**Comment by HyperDenton** [comment]
> This example uses pion you better ask them this question https://github.com/pion/webrtc

Thanks! I'm closing the issue and give an update as soon as I find the solution. :)

**Comment by HyperDenton** [comment]
I just found one possible solution to limit port range on [pion#282](https://github.com/pion/webrtc/pull/282). To use it, just add a few lines in [http.go](https://github.com/deepch/RTSPtoWebRTC/blob/master/http.go#L128):

`		// api := webrtc.NewAPI(webrtc.WithMediaEngine(mediaEngine))
		settings := webrtc.SettingEngine{}
		settings.SetEphemeralUDPPortRange(8084, 8090) // set port range to (8084, 8090]

		api := webrtc.NewAPI(webrtc.WithMediaEngine(mediaEngine), webrtc.WithSettingEngine(settings))`

which is much more "firewall-friendly" and "docker-friendly". BTW, shall I pull request to add this feature since random WebRTC ports can be a little bit confusing?

**Comment by HyperDenton** [comment]
I just found one possible solution to limit port range on [pion#282](https://github.com/pion/webrtc/pull/282). To use it, just add a few lines in [http.go](https://github.com/deepch/RTSPtoWebRTC/blob/master/http.go#L128), line 128:

```
 // api := webrtc.NewAPI(webrtc.WithMediaEngine(mediaEngine))
settings := webrtc.SettingEngine{}
settings.SetEphemeralUDPPortRange(8084, 8090) // set port range to (8084, 8090]
api := webrtc.NewAPI(webrtc.WithMediaEngine(mediaEngine), webrtc.WithSettingEngine(settings))
```
which is much more "firewall-friendly" and "docker-friendly". 

BTW, shall I pull request to add this feature since random WebRTC ports can be a little bit confusing?
