### ISSUE TITLE
hope support rtsp to webrtc  by h265 (use golang,not use ffmpeg )

### ISSUE THREAD

**Issue by z-feiyu** [deepch/RTSPtoWebRTC#41]

**Comment by deepch** [comment]
Chromium engine does not support h265 due to license issues
https://stackoverflow.com/questions/36382568/h-265-hevc-web-browser-support

sorry need transcode h265 to h264 or av1

**Comment by EdmundHerbert** [comment]
Hi when will H265 support be available more and more cameras are now only H265

I would be willing to contribute financially to get this done

regards

Edmund Herbert
