### ISSUE TITLE
pion webrct v2 missing

### ISSUE THREAD

**Issue by ZelleAP** [deepch/RTSPtoWebRTC#43]
If I will get the packed I become this errror:
go get github.com/deepch/RTSPtoWebRTC
package github.com/pion/webrtc/v2: cannot find package "github.com/pion/webrtc/v2" in any of:
        /usr/lib/go-1.10/src/github.com/pion/webrtc/v2 (from $GOROOT)
        /root/go/src/github.com/pion/webrtc/v2 (from $GOPATH)

**Comment by ajs3** [comment]
Had the same issue here

**Comment by deepch** [comment]
GO111MODULE=on go get github.com/deepch/RTSPtoWebRTC

**Comment by gismofx** [comment]
I'm not a go expert, but receiving a similar error and tried the above as suggested and see this error now: (I'm using  `go version go1.15.5 windows/amd64`)

```
PS C:\go> GO111MODULE=on go get github.com/deepch/RTSPtoWebRTC
GO111MODULE=on : The term 'GO111MODULE=on' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ GO111MODULE=on go get github.com/deepch/RTSPtoWebRTC
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (GO111MODULE=on:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by deepch** [comment]
updated v3
