### ISSUE TITLE
"crypto/ed25519": missing dot in first path element

### ISSUE THREAD

**Issue by cedricve** [deepch/RTSPtoWebRTC#45]
I'm getting it with go version go1.13.3 darwin/amd64

        go: finding github.com/pborman/uuid v1.2.0
        build github.com/micro/micro: cannot load crypto/ed25519: malformed module path "crypto/ed25519": missing dot in first path element

**Comment by cedricve** [comment]
@deepch any idea here?

**Comment by deepch** [comment]
try

https://github.com/deepch/RTSPtoWebRTC/issues/43#issuecomment-689783815

**Comment by cedricve** [comment]
hmm same issue..

    $  go version
    go version go1.13.3 darwin/amd64
