### ISSUE TITLE
how to save the source stream (in chunks)?

### ISSUE THREAD

**Issue by dottgonzo** [deepch/RTSPtoWebRTC#46]
hi,
i'm not able to understand how to store the source stream (chunked) as flv/mp4, can anyone help me?

**Comment by deepch** [comment]
you need mp4 or raw h264?

**Comment by deepch** [comment]
open file to write and mux chunk annexB 

and play ffplay test.h264

`if pkt.IsKeyFrame {
				chunk = append([]byte{0, 0, 0, 1}, bytes.Join([][]byte{codec.SPS(), codec.PPS(), pkt.Data[4:]}, []byte{0, 0, 0, 1})...)
			} else {
				chunk = pkt.Data[4:]
			}`

if you need m4 or ts look doc vdk

**Comment by dottgonzo** [comment]
thanks! i'm running to test it now!

i think that to store the stream captured from the cam is better to use the raw h264 and the flv format, and then, when the chunk is completed, to convert it to mp4. What do you think?

My goal is to get the stream from a cam, store it, and to stream to many client (with (if needed) and without transcoding it)

**Comment by deepch** [comment]
you can make mp4  https://github.com/deepch/vdk/blob/master/format/mp4/muxer.go 

1) NewMuxer
2) WriteHeader
3) WritePacket
4) WriteTrailer

you can calc time look pkt.Time and write logic 

if  pkt.Time - fistTS convert second > 60 start write to file N count frame and etc......

**Comment by dottgonzo** [comment]
thanks for all, i was just able to use pkt.TIme, now i'm implementing your tip for mp4. Thanks for all :+1:

**Comment by imamiao** [comment]
Hi! I want to implement this function on this project: save a period of time (for example, 10 seconds) of video to the disk at a certain point in time.
I am a novice to Go language. Is it difficult to implement? Can you briefly talk about the implementation steps. Thank you very much!

**Comment by Mosphere** [comment]
> thanks! i've added your code to the stream.go file and it works (with h26h codec)!
> 
> if i want to generate a new chunk file every x minutes, how i can calculate when is the time to generate a new chunk file? maybe by counting the key frame? or by number of bytes? or i need to rely to the os datetime?

Could you please give a code example of saving rtsp stream to h264 file while casting in webrtc,Thanks!
