### ISSUE TITLE
codec error 

### ISSUE THREAD

**Issue by cedricve** [deepch/RTSPtoWebRTC#47]
I'm getting a codec error when using this public RTSP url: rtsp://wowzaec2demo.streamlock.net:554/vod/mp4:BigBuckBunny_115k.mov

        2020/10/13 13:38:19 Request demo1
        2020/10/13 13:38:19 Codec error
        [GIN] 2020/10/13 - 13:38:19 | 200 |     451.752µs |             ::1 | POST     "/recive"
        [GIN] 2020/10/13 - 13:38:19 | 404 |         859ns |             ::1 | GET      "/favicon.ico"
        rtp: keep alive
        > OPTIONS rtsp://wowzaec2demo.streamlock.net:554/vod/mp4:BigBuckBunny_115k.mov RTSP/1.0

This is the config

        {
          "server": {
            "http_port": ":8083"
          },
          "streams": {
            "demo1": {
              "url": "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov"
            }
          }
        }

**Comment by cedricve** [comment]
@deepch do you have any thoughts?

**Comment by AlexxIT** [comment]
This link also doesn't work for me. But the cameras work without problems

**Comment by deepch** [comment]
try new version
