### ISSUE TITLE
Video might not work with codec 102

### ISSUE THREAD

**Issue by cedricve** [deepch/RTSPtoWebRTC#48]
I get this error while setting up the client connection from the front-end. Any idea?

**Comment by vigggen** [comment]
I'm getting the same error. 

2020/11/05 16:03:17 Request CAM1
2020/11/05 16:03:17 Video might not work with codec 102
2020/11/05 16:03:17 Work payloadType 102 
rtp: keep alive
> OPTIONS rtsp://10.20.55.148:88/live/video_audio/profile2 RTSP/1.0
CSeq: 6

[GIN] 2020/11/05 - 16:03:22 | 200 |    5.0418571s |    10.20.55.129 | POST     "/recive"
2020/11/05 16:03:22 Connection State has changed checking
2020/11/05 16:03:22 Client Close Exit
2020/11/05 16:03:22 Connection State has changed closed
2020/11/05 16:03:22 Client Close Exit
rtp: keep alive
> OPTIONS rtsp://10.20.55.148:88/live/video_audio/profile2 RTSP/1.0

**Comment by deepch** [comment]
I'm sorry I'm sick. I will answer your questions later.

**Comment by AlexxIT** [comment]
Codec 102 is not a problem

```
2020/11/11 10:58:00 Request Sonoff
2020/11/11 10:58:00 Video might not work with codec 102
2020/11/11 10:58:00 Work payloadType 102
[GIN] 2020/11/11 - 10:58:00 | 200 |   89.889597ms |  192.168.1.123 | POST     "/recive"
2020/11/11 10:58:00 Connection State has changed connected 
2020/11/11 10:58:00 start stream Sonoff client ....
```

**Comment by yeshivsher** [comment]
> I'm sorry I'm sick. I will answer your questions later.

Have the same problem can you answer please?

**Comment by yeshivsher** [comment]
> Codec 102 is not a problem
> 
> ```
> 2020/11/11 10:58:00 Request Sonoff
> 2020/11/11 10:58:00 Video might not work with codec 102
> 2020/11/11 10:58:00 Work payloadType 102
> [GIN] 2020/11/11 - 10:58:00 | 200 |   89.889597ms |  192.168.1.123 | POST     "/recive"
> 2020/11/11 10:58:00 Connection State has changed connected 
> 2020/11/11 10:58:00 start stream Sonoff client ....
> ```

it is a problem for me, what do you mean?

**Comment by deepch** [comment]
Try it in the new version there pion v3 was updated and rtsp v2 client was updated
