### ISSUE TITLE
SSL / HTTPS

### ISSUE THREAD

**Issue by myhometendance** [deepch/RTSPtoWebRTC#49]
A solution to run through HTTPS / SSL ?

Website on Apache with SSL certificate...
Apache proxy ?

I try to test Webrtc player on webpage but Chrome refuse because of mixed content .. 

Thank.

**Comment by deepch** [comment]
you can use https://github.com/gin-gonic/autotls
only web server need https

**Comment by myhometendance** [comment]
Ok thank it works

But now i don't anderstand wich port number open on the firewall.

When i open the port 8083, web interface works properly but no image.
When i open the dmz on the server all work but i wish open only the the necessary ports.

Thank in advance

**Comment by deepch** [comment]
Try pointing your question to the pion developers or looking for an answer in their tracker.

https://github.com/pion/webrtc

**Comment by AlexxIT** [comment]
App also open UDP ports for real-time translation `netstat -tulpn | grep RTSP`

I am trying to figure out how to share my camera on the Internet.

**Comment by avoskresenskiy-alytics** [comment]
to run WebRTC with TSL replace this line in http.go:
err := router.Run(Config.Server.HTTPPort)

with this one:
err := router.RunTLS(8443, "/etc/letsencrypt/live/domain.ru/fullchain.pem", "/etc/letsencrypt/live/domain.ru/privkey.pem")

you can get free certificates with certbot (Lets Encrypt).

Then open https://domain.ru:8443
