### ISSUE TITLE
Wowza test rtsp stream not working;

### ISSUE THREAD

**Issue by NovelCorpse** [deepch/RTSPtoWebRTC#5]
Hello, @deepch !

I tried to use your sample, but wowza test rtsp stream (for example: rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov or rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov) not played. 
I have checked via ffplay, vlc and every stream worked. What is the reason for this? Maybe your sample work only with rtsp stream from webcam?

I would appreciate for your reply.
Best regard, Roman.

**Comment by deepch** [comment]
In this case, the code is an example that it can work.
Your stream gives the first audio stream a after the video.
The current code does not see the difference that would have earned your option is enough to choose a different flow number

replace

`if data[0] == 36 && data[1] == 0 {`

to

`if data[0] == 36 && data[1] == 1 {`

![Снимок экрана 2019-07-14 в 22 32 39](https://user-images.githubusercontent.com/7899955/61188491-5e567c00-a688-11e9-943d-e29d5c688e23.png)



I recommend checking on RTSP cameras for example

`rtsp://admin:1234567@171.25.235.18/mpeg4`

**Comment by deepch** [comment]
maybe later I will update this code to a more modern one.
2
