### ISSUE TITLE
"Fix Format may be raw PCM 97 97"

### ISSUE THREAD

**Issue by sirisian** [deepch/RTSPtoWebRTC#50]
I have an RTSP server where I modified a standard h264 main profile with aac audio stream using:

```
ffmpeg -rtsp_transport udp -i rtsp://10.0.0.10/main -vcodec copy -acodec pcm_alaw -f rtsp rtsp://....
```

When the RTSPtoWebRTC connects to the stream it outputs "Fix Format may be raw PCM 97 97" then says "exit status 1" and stops. I've tested the stream with VLC and it plays video/audio. I've also tried pcm_mulaw with the same message. ffmpeg supports a lot of PCM variants. https://trac.ffmpeg.org/wiki/audio%20types 

Not sure what the raw PCM 97 97 refers to exactly.

I should point out that RTSPtoWebRTC plays the video fine with the original rtsp://10.0.0.10/main stream and drops the aac audio as expected. (I need audio though which is why I'm jumping through this hoop of converting it).

**Comment by deepch** [comment]
ok add next version.

**Comment by greendrake** [comment]
I am getting this error simply trying to serve an RTSP stream which VLC sees as:

![Screenshot from 2020-11-08 01-51-27](https://user-images.githubusercontent.com/1991299/98441735-186ad480-2165-11eb-951f-187b49dd994c.png)

RTSPtoWebRTC runs and exits:

```
root@rtsp:~# ./RTSPtoWebRTC 
2020/11/07 12:53:41 Server Start Awaiting Signal
2020/11/07 12:53:41 stream-1 connect rtsp://127.0.0.1/stream-1
> OPTIONS rtsp://127.0.0.1:554/stream-1 RTSP/1.0
CSeq: 1

> DESCRIBE rtsp://127.0.0.1:554/stream-1 RTSP/1.0
CSeq: 2
Accept: application/sdp

< v=0
o=- 1604752801147935 1 IN IP4 172.17.0.10
s=LIVE555 Streaming Media v2020.11.05
i=LIVE555 Streaming Media v2020.11.05
t=0 0
a=tool:LIVE555 Streaming Media v2020.11.05
a=type:broadcast
a=control:*
a=range:npt=0-
a=x-qt-text-nam:LIVE555 Streaming Media v2020.11.05
a=x-qt-text-inf:LIVE555 Streaming Media v2020.11.05
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:50
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=4D0029;sprop-parameter-sets=J00AKY1uB4AiflhAAAADAEAAAAyh,KO4DnIA=
a=control:track1
m=audio 0 RTP/AVP 97
c=IN IP4 0.0.0.0
b=AS:50
a=rtpmap:97 PCMA/8000
a=control:track2

2020/11/07 12:53:41 Fix Format may be raw PCM 97 97
```

**Comment by deepch** [comment]
Try it in the new version there pion v3 was updated and rtsp v2 client was updated

**Comment by yeshivsher** [comment]
getting this error 
Fix Format may be raw PCM 97 96
when I try to connect to several rtsp s
