### ISSUE TITLE
Concurrent use issue

### ISSUE THREAD

**Issue by rcbull** [deepch/RTSPtoWebRTC#51]
I'm trying to use the repository to connect multiple cameras (using RTSP), keeping different instances of the executable running, but often there is a connection problem or on the second attempt the previous connection is closed.

![image](https://user-images.githubusercontent.com/451853/97293609-ae306680-182b-11eb-9153-90921c756036.png)

Another problem is disconnecting the RTCDatachannel after a few minutes, reporting message:

`adapter-latest.js:1461 Uncaught DOMException: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'`

Do you have any suggestions for a solution to the problem?

Regards

**Comment by cedricve** [comment]
Hey,

The data channel is closed by the Go project, and thus closes the data channel in the js code. As their is a setInterval in the code, which is not cleaned up, it will keep sending to a closed channel.

**Comment by rcbull** [comment]
Ok @cedricve 

I added a condition to send only channel is open, but I can't track the connection drop. Sometimes the system stay connected for a few hours, sometimes a few seconds.

`
if(sendChannel.readyState == "open") {
    sendChannel.send('ping');
}`

**Comment by deepch** [comment]
I'm sorry I'm sick. I will answer your questions later.

**Comment by deepch** [comment]
Try it in the new version there pion v3 was updated and rtsp v2 client was updated
