### ISSUE TITLE
ICE connection state changes to "Disconnected" 30 seconds after it connected in complex NAT

### ISSUE THREAD

**Issue by yourchanges** [deepch/RTSPtoWebRTC#52]
### Your environment.
  - Version: pion/webrtc v2.2.24
  - Browser: chrome 86.0.4240.111 64bit
  - Other Information 
turn server(gortcd) config

```
peerConnection, err := api.NewPeerConnection(webrtc.Configuration{
			ICEServers: []webrtc.ICEServer{

				{
					URLs: []string{"turn:xxx.xxx.xxx.xxx:3478"},
					Username: "webrtc",
					Credential:"google",
					CredentialType:webrtc.ICECredentialTypePassword,
				},
			},
		})
```

### What did you do?
I just run the https://github.com/deepch/RTSPtoWebRTC lastest version

deploy it a public ip server, when my browser and RTSPtoWebRTC server in the same LAN, it works normally.

when I open the browser in the other network env, it can open the webrtc vedio stream, the data channel is ok, but it will disconnected in 30 seconds.

### What did you expect?

it works  or  give some tips how to work around.
### What happened?

server side log:
```
2020/10/30 21:51:46 Connection State has changed connected 
2020/10/30 21:51:46 complete
2020/10/30 21:51:46 start stream HQ-3 client 7F5EB57B-2EC8-D515-9BC5-A46E1F4D0CE3
2020/10/30 21:52:17 Client Close Keep-Alive Timer
2020/10/30 21:52:17 Connection State has changed closed 
2020/10/30 21:52:17 complete
2020/10/30 21:52:17 Client Close Exit
2020/10/30 21:52:17 stop stream HQ-3 client 7F5EB57B-2EC8-D515-9BC5-A46E1F4D0CE3

```
chrome browser log:
```
add video Transceiver
checking
1 track is delivered
connected
disconnected
```
chrome webrtc internal

```
Time	Event
2020/10/30 9:51:46	
createLocalDataChannel
2020/10/30 9:51:46	negotiationneeded
2020/10/30 9:51:46	
createOffer
2020/10/30 9:51:46	
createOfferOnSuccess
2020/10/30 9:51:46	
setLocalDescription
2020/10/30 9:51:46	
transceiverModified
2020/10/30 9:51:46	
signalingstatechange
2020/10/30 9:51:46	setLocalDescriptionOnSuccess
2020/10/30 9:51:46	
icegatheringstatechange
2020/10/30 9:51:46	
icecandidateerror
2020/10/30 9:51:46	
icecandidateerror
2020/10/30 9:51:46	
icecandidate (host)
2020/10/30 9:51:46	
icecandidate (host)
2020/10/30 9:51:46	
icecandidate (srflx)
2020/10/30 9:51:46	
icecandidate (srflx)
2020/10/30 9:51:46	
setRemoteDescription
2020/10/30 9:51:46	
iceconnectionstatechange
2020/10/30 9:51:46	
transceiverModified
2020/10/30 9:51:46	
signalingstatechange
2020/10/30 9:51:46	setRemoteDescriptionOnSuccess
2020/10/30 9:51:46	
iceconnectionstatechange (legacy)
2020/10/30 9:51:46	
connectionstatechange
2020/10/30 9:51:46	
icecandidate (relay)
2020/10/30 9:51:46	
icegatheringstatechange
2020/10/30 9:51:46	
iceconnectionstatechange
2020/10/30 9:51:46	
iceconnectionstatechange (legacy)
2020/10/30 9:51:46	
connectionstatechange
2020/10/30 9:52:01	
iceconnectionstatechange (legacy)
completed
2020/10/30 9:52:16	
iceconnectionstatechange
2020/10/30 9:52:16	
iceconnectionstatechange (legacy)
connected
2020/10/30 9:52:16	
iceconnectionstatechange (legacy)
failed
2020/10/30 9:52:16	
connectionstatechange
failed
```

**Comment by lxb531** [comment]
```
	case <-timer1.C:
		log.Println("Client Close Keep-Alive Timer", suuid)
		**// peerConnection.Close()**
```

**Comment by yeshivsher** [comment]
can you share how you solved it and how you added the Turn server capability?
I have the same problem.
works locally but blank page in NAT.

**Comment by yourchanges** [comment]
> ```
> 	case <-timer1.C:
> 		log.Println("Client Close Keep-Alive Timer", suuid)
> 		**// peerConnection.Close()**
> ```

it's not a problem with a worked web-rtc data channel heart-beat.



> can you share how you solved it and how you added the Turn server capability?
> I have the same problem.
> works locally but blank page in NAT.

we change our turn server(gortcd) to coturn server with some special configuration, it works in complex NAT env, including wifi and 3G/4G/5G

**Comment by deepch** [comment]
Try it in the new version there pion v3 was updated and rtsp v2 client was updated

**Comment by DrewZt** [comment]
> > ```
> > 	case <-timer1.C:
> > 		log.Println("Client Close Keep-Alive Timer", suuid)
> > 		**// peerConnection.Close()**
> > ```
> 
> it's not a problem with a worked web-rtc data channel heart-beat.
> 
> > can you share how you solved it and how you added the Turn server capability?
> > I have the same problem.
> > works locally but blank page in NAT.
> 
> we change our turn server(gortcd) to coturn server with some special configuration, it works in complex NAT env, including wifi and 3G/4G/5G

can you share your configuration of coturn? I tried it but still does not work

**Comment by naveenrobo** [comment]
Kindly share the coturn config for cross verification. We are facing similar problem.

**Comment by yourchanges** [comment]
trunserver.conf
```
listening-device=eth0
listening-port=13478
relay-device=eth0
external-ip=10x.2x.11.xx
listening-ip=10x.2x.11.xx
min-port=13480
max-port=23500
fingerprint
lt-cred-mech
realm=ice.xxx.cxx
cert=/usr/local/etc/turn_server_cert.pem
pkey=/usr/local/etc/turn_server_pkey.pem
no-multicast-peers
mobility
no-cli
```

start cmd:
```
/usr/local/bin/turnserver -o -a -f --mobility -m 20 --max-bps=100000000000 --min-port=32355 --max-port=65000 --user=webrtc:xxxxx -r xxx.xxx.xxx
```

**Comment by MuzmmilKhan1** [comment]
@yourchanges Could you please help me I don't have any turn_server_cert.pem and turn_server_pkey.pem in /usr/local/etc/ 
Thanks

**Comment by yourchanges** [comment]
@MuzmmilKhan1 just check https://github.com/coturn/coturn/tree/master/examples/etc pls.

**Comment by MuzmmilKhan1** [comment]
> @MuzmmilKhan1 just check https://github.com/coturn/coturn/tree/master/examples/etc pls.

Thanks Mate
