### ISSUE TITLE
cannot find module for path crypto/ed25519

### ISSUE THREAD

**Issue by hillout** [deepch/RTSPtoWebRTC#56]
Hi! Trying to go run . command on RPI4, and eventually it fails with this error: 

build github.com/deepch/RTSPtoWebRTC: cannot find module for path crypto/ed25519

Can you help please?

**Comment by AntiHeld889** [comment]
Same problem

**Comment by yeshivsher** [comment]
What version of Go you running?
What OS Linux or Windows?

**Comment by hillout** [comment]
Hi,
Mine:

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Kernel: 5.4.72-v7l+

Go version go1.11.6 linux/arm

**Comment by yeshivsher** [comment]
Maybe upgrade the go version will fix it.
I recommend you to do it on docker - you will not see any error.

**Comment by hillout** [comment]
You mean, a container with Go lang only?

**Comment by best4username** [comment]
same also

**Comment by deepch** [comment]
Try it in the new version there pion v3 was updated and rtsp v2 client was updated
