### ISSUE TITLE
Make it work in a different service using js only

### ISSUE THREAD

**Issue by yeshivsher** [deepch/RTSPtoWebRTC#57]
I want to use this great project as a service that I'm installing in a computer, and create another service in js (React in my case) and publish this front-end to a cloud for example.

I don't familiar with Go so can someone help me in how to create a service that will connect to this Go service?

Something like that:
1. go . run (service 1 on port xxx)
2. npm start  (service 2 on port yyy)

Thanks

**Comment by mxzinke** [comment]
Just build this repository in a docker container with an entry-point:

```Dockerfile
FROM golang:1.15-alpine AS build
WORKDIR /app

COPY . .

RUN go build -o build .

# Running Stage
FROM alpine:latest
WORKDIR /app

COPY --from=build /app/build ./build

ENTRYPOINT [ "./build" ]
```

Then you can start it with ```docker run -v `pwd`/config.json:/app/config.json your-build:latest```. I think you are able to specify the port in the config. Then you are going to deploy you second application and use the REST API to interact with this service. There are already ready to go WebRTC packages for React.js.

**Comment by yeshivsher** [comment]
Did you try this service remotely?

**Comment by mxzinke** [comment]
Sorry for late response.

Yes, I did try it, but I actually modified it a bit to fit my requirements. Should be fine for you.

**Comment by deepch** [comment]
fixed patch https://github.com/deepch/RTSPtoWebRTC/commit/e9cb442099ba2cb46a92e82741550eedf615f76c

**Comment by deepch** [comment]
and https://github.com/deepch/RTSPtoWebRTC/commit/39053c76f2ffa166dbeaf5d8044ad25df29939ce
