### ISSUE TITLE
Go over remote server

### ISSUE THREAD

**Issue by yeshivsher** [deepch/RTSPtoWebRTC#58]
I run  this project on a windows server.
locally it works great but when I'm going from different network the page is displayed and everything is fine except the video that not showing up.

No error and no "sendChannel has opened" message.

Any ideas?

**Comment by kasdovel** [comment]
I have a very similar problem.
I want to publish this service to my server, but before that I tried to run it on docker container.
When I run this on a container, I can't see the video. The UI works great, but I can't see any video [it keeps loading...].
This is the logs: 
[GIN] 2020/12/24 - 18:10:25 | 200 |          64µs |      172.17.0.1 | GET      "/static/css/bootstrap.min.css.map"
"/codec/camera_2"
2020/12/24 18:10:25 Request camera_2                                            /codec/camera_2"
2020/12/24 18:10:25 Video might not work with codec 102
2020/12/24 18:10:25 Work payloadType 102
[GIN] 2020/12/24 - 18:10:25 | 200 |     97.4332ms |      172.17.0.1 | POST     "
"/recive"                                                                       /recive"

2020/12/24 18:10:35 Connection State has changed failed
2020/12/24 18:10:35 Client Close Exit
2020/12/24 18:10:35 Connection State has changed closed
2020/12/24 18:10:35 Client Close Exit

**Comment by yeshivsher** [comment]
Don't have a solution yet 
If you solve it please let me know

**Comment by deepch** [comment]
maybe it makes sense to look in the new version it is still in work, but I can give you access. To invite?

**Comment by kasdovel** [comment]
> maybe it makes sense to look in the new version it is still in work, but I can give you access. To invite?

Yes, I would like to get an access.

**Comment by deepch** [comment]
https://github.com/deepch/RTSPtoWeb

**Comment by yeshivsher** [comment]
Wow cool!
What is the difference from the RTSPtoMp4 project?

**Comment by deepch** [comment]
This will merge webrtc mse hls

**Comment by kasdovel** [comment]
> This will merge webrtc mse hls

What does it mean?

**Comment by deepch** [comment]
it's a whole bunch of technologies to help you deliver videos to different devices.
