### ISSUE TITLE
RTSP OPUS Support

### ISSUE THREAD

**Issue by bbnp91** [deepch/RTSPtoWebRTC#59]
Hi, 

Any chance of having an opus rtsp stream supported in this project?
I am trying to convert an audio only rtsp stream using the opus codec into WebRTC.

**Comment by deepch** [comment]
I admit honestly, I have never seen the rtsp stream with opus, but there is an option to make pcm pama pcmu, like it was added in the new version of pion.

**Comment by bbnp91** [comment]
PCM is much higher bandwidth and latency than OPUS so not suitable to stream to lots of people at the same time. I can provide Opus RTSP test stream is you need. 

It would be great to add OPUS audio only support into this project. I will buy lots of tea :)

**Comment by deepch** [comment]
yes it is reasonable

on something I need to conduct tests.

Is there an example of a stream with opus (available on white ip)?
Or maybe the software that streams rtsp opus?

**Comment by bbnp91** [comment]
OK thanks. 

You can create OPUS rtsp stream by using this ffmpeg command and streaming to a RTSP server.

> ffmpeg -re -stream_loop -1 -i testfile.mp3 -vn -c:a libopus -ab 128k -f rtsp rtsp://$SERVERADDRESS:554/mystream

If you need you can use this test stream ffplay rtsp://35.213.193.100:554/opus to try.

**Comment by deepch** [comment]
im start work 

`rtsp://35.213.193.100:554/opus`

`ffplay -rtsp_transport tcp rtsp://35.213.193.100:554/opus`

`method SETUP failed: 461 Unsupported Transport`

you can add tcp transport

**Comment by bbnp91** [comment]
TCP is enabled now.

**Comment by deepch** [comment]
worked thx

**Comment by deepch** [comment]
PCM_ALAW PCM_MULAW and OPUS worked
need upgrade source and module 

please check it

<img width="1351" alt="Снимок экрана 2021-01-09 в 17 24 06" src="https://user-images.githubusercontent.com/7899955/104094141-183fa000-52a0-11eb-9a23-a09e4d4096d4.png">

**Comment by bbnp91** [comment]
Amazing work. Thank you, it works very well.

**Comment by deepch** [comment]
Thanks, good luck.
