### ISSUE TITLE
Is it possible to just forward RTP packet from RTSP to WebRTC

### ISSUE THREAD

**Issue by wuchihsu** [deepch/RTSPtoWebRTC#6]
Hi @deepch ,

I'm new to video streaming. I just know that RTSP and WebRTC all transport RTP packets. But it seems that you repacketize it before sending it. So is it possible to just forward RTP packet from RTSP to WebRTC?

**Comment by deepch** [comment]
Theoretical Yes but they should be encrypted on how many I remember srtp without it it will not work and also webrtc is necessary as RTSP for coordination of a number of the moments such as SDP codecs and transport for nat

**Comment by wuchihsu** [comment]
OK, I need some time to figure this out. Thanks!
