### ISSUE TITLE
Install On nginx server cent OS

### ISSUE THREAD

**Issue by lianmafutra** [deepch/RTSPtoWebRTC#60]
I've tried it locally and it works,
but after installed it on the video server and access the ip url: 8083/player/demo1 , it couldn't be played, blank screen

terminal  log:
2020/12/18 22:03:21 Connection State has changed failed 
2020/12/18 22:03:21 Client Close Exit
2020/12/18 22:03:21 Connection State has changed closed 
2020/12/18 22:03:21 Client Close Exit

**Comment by deepch** [comment]
Please show the full log.

**Comment by deepch** [comment]
Try it in the new version there pion v3 was updated and rtsp v2 client was updated
