### ISSUE TITLE
Video only mode?

### ISSUE THREAD

**Issue by mattbrad2** [deepch/RTSPtoWebRTC#63]
I would love to integrate this into a home security monitoring system but would need a version without the menu's; just the video output. Would also be great to have web hooks to change the video stream remotely without displaying the buttons. I've looked through the js but it appears the html is built up in more than one place.

**Comment by deepch** [comment]
understand this is just an example that it works. Not a ready-made solution.
I can do what you ask, but there should be a clear task.

**Comment by mattbrad2** [comment]
Oh of course. I understand. I just figured I would ask to at least see how feasible it would be to pull off. I know the Home Assistant community has been asking for something similar, since someone has made a plugin based on RSTPtoWebRTC. 

Essentially, I would like to run a kiosk browser and have it point to the stream URL but just show the video without any of the log data, title, button, etc. Think of it as a security monitor that just displays a camera feed full screen. 

Since we're removing the buttons to change camera feeds, this would need to be done through an API of sorts. Simple webhooks that would change the current camera feed to another one defined in the JSON config. You could then control a realtime camera feed via Zapier, etc.

**Comment by deepch** [comment]
try https://github.com/deepch/RTSPtoWeb

**Comment by deepch** [comment]
or use 

`	RTSPClient, err := rtspv2.Dial(rtspv2.RTSPClientOptions{URL: url, DisableAudio: true, DialTimeout: 3 * time.Second, ReadWriteTimeout: 3 * time.Second, Debug: false})`

`
DisableAudio: true
`

**Comment by vegalou** [comment]
Maybe you could modify player's template and add element adjustment in JS & CSS

    ./web/templates/player.tmpl

Mapping channel to config.json naming.
