### ISSUE TITLE
Upgrade to pion/webrtc@v3

### ISSUE THREAD

**Issue by Sean-Der** [deepch/RTSPtoWebRTC#64]
Hey @deepch 

I released [v3](https://github.com/pion/webrtc/wiki/Release-WebRTC%40v3.0.0) and would love to help you upgrade, I can make the PR. If you want to wait/have any questions happy to answer them. 

API wise I this should make it a lot easier for users. The Track API has seen major changes. It handles the SSRC/PayloadType internally so you don't need to manage. It also enables Trickle ICE by default. You can disable it if you wish, but it could mean faster connect times.

**Comment by deepch** [comment]
I tried using it but only got a black screen. Trickle ICE enables - and you can learn more about how to disable it

I will update the project to version pion v3 today.

**Comment by Sean-Der** [comment]
You can disable like [this](https://github.com/pion/webrtc/wiki/Release-WebRTC%40v3.0.0#helper-function-to-simulate-non-trickle-ice) we provide `GatheringCompletePromise`

So it connects but you get a black screen? Maybe the codecs are configured wrong. If you can push to a branch would love to help debug!

**Comment by deepch** [comment]
ready migrated worked on pion v3.
need test audio pcm

there is some kind of bug with timestamps audio.

https://github.com/deepch/vdk/blob/1b7359bceb450b427ac4c769ba35a35b5d4a5e79/format/webrtcv3/adapter.go#L161

I'll try to figure it out tomorrow.

**Comment by deepch** [comment]
ready migrated worked on pion v3.
need test audio pcm

there is some kind of bug with timestamps.

https://github.com/deepch/vdk/blob/1b7359bceb450b427ac4c769ba35a35b5d4a5e79/format/webrtcv3/adapter.go#L161

I'll try to figure it out tomorrow, not very pretty yet, but overall it works.

**Comment by Sean-Der** [comment]
Nice! This is my timing code I used in rtsp-bench https://github.com/pion/rtsp-bench/blob/master/server/main.go#L175-L179

**Comment by deepch** [comment]
Same result.

cur - pre = ts 

Sample work only video track no audio. 
Problem video + audio (pcm)

**Comment by deepch** [comment]
I think it's a little thing tonight I'll do everything.

Thank you for your help!
good luck to you

**Comment by AlexxIT** [comment]
Hi @Sean-Der, you and @deepch doing great job!

Based on @deepch's project, I made a Home Assistant addon. Including working external access to users cameras. It already has many satisfied users. I think you would be pleased to know:

https://community.home-assistant.io/t/realtime-camera-streaming-without-any-delay-rtsp2webrtc/258216

**Comment by deepch** [comment]
Hi @AlexxIT Great job. Continue in the same spirit. 
It is very nice that you help people and a little later I will test your adon.

**Comment by deepch** [comment]
@AlexxIT Вы можете писать и по русский я пойму ;)

**Comment by Sean-Der** [comment]
That is so awesome! I posted on our Twitter :) https://mobile.twitter.com/_pion/status/1348845305693802503

you should also add to awesome-pion!
