### ISSUE TITLE
Can not work in CentOS 7

### ISSUE THREAD

**Issue by hujinlong** [deepch/RTSPtoWebRTC#65]
client：Chrome brower
（1）RTSPtoWebRTC run in windows 7，ok
（2）RTSPtoWebRTC run in CentOS，ng
server logs:
[GIN-debug] Listening and serving HTTP on :8083
[GIN] 2021/01/10 - 16:47:34 | 200 |    1.086015ms |   192.168.21.21 | GET      "/player/H264_Dahua"
[GIN] 2021/01/10 - 16:47:34 | 200 |     817.018µs |   192.168.21.21 | GET      "/static/js/app.js?ver=2021-01-10%2016%3a47%3a34.494850575%20%2b0800%20CST%20m%3d%2b3.175192244"
[GIN] 2021/01/10 - 16:47:34 | 200 |    9.115547ms |   192.168.21.21 | GET      "/static/js/bootstrap.min.js.map"
[GIN] 2021/01/10 - 16:47:34 | 200 |     227.211µs |   192.168.21.21 | GET      "/codec/H264_Dahua"
[GIN] 2021/01/10 - 16:47:34 | 200 |   47.183808ms |   192.168.21.21 | GET      "/static/css/bootstrap.min.css.map"
[GIN] 2021/01/10 - 16:47:34 | 200 |   33.783239ms |   192.168.21.21 | POST     "/recive"
[GIN] 2021/01/10 - 16:47:41 | 200 |     854.681µs |   192.168.21.21 | GET      "/player/H264_Haikang"
[GIN] 2021/01/10 - 16:47:41 | 200 |     201.148µs |   192.168.21.21 | GET      "/static/js/app.js?ver=2021-01-10%2016%3a47%3a41.751345133%20%2b0800%20CST%20m%3d%2b10.431686815"
[GIN] 2021/01/10 - 16:47:41 | 200 |      38.691µs |   192.168.21.21 | GET      "/codec/H264_Haikang"
[GIN] 2021/01/10 - 16:47:41 | 200 |     589.005µs |   192.168.21.21 | GET      "/static/js/bootstrap.min.js.map"
[GIN] 2021/01/10 - 16:47:41 | 200 |    8.213368ms |   192.168.21.21 | POST     "/recive"
[GIN] 2021/01/10 - 16:47:41 | 200 |   62.519707ms |   192.168.21.21 | GET      "/static/css/bootstrap.min.css.map"
2021/01/10 16:47:54 Client Not Send ACK (probably the browser is minimized) or tab not active Close client
2021/01/10 16:47:54 Stream Not Send Video Close
2021/01/10 16:47:54 WritePacket WebRTC Client Offline
2021/01/10 16:48:01 Client Not Send ACK (probably the browser is minimized) or tab not active Close client
2021/01/10 16:48:01 WritePacket WebRTC Client Offline

something was wrong at web client javascript code?but chrome brower console cant see any error tips.

**Comment by hujinlong** [comment]
when i stop my server`s firewall service,the problem solved.
firewall need open some udp ports?

**Comment by deepch** [comment]
new version added options, you can use config 

`"server": {
  "http_port": ":8083",
  "ice_servers": ["stun:stun.l.google.com:19302"],
  "webrtc_port_min": 50000,
  "webrtc_port_max": 50009
},`

configure ice and udp port range
