### ISSUE TITLE
adjust size of rtsp cache or buffer

### ISSUE THREAD

**Issue by kakusikun** [deepch/RTSPtoWebRTC#66]
is there any config, setting, or even code that can adjust the size of rtsp data buffer or cache to find the optimal choice to lower the latency?

**Comment by kakusikun** [comment]
https://github.com/deepch/RTSPtoWebRTC/blob/master/config.go#L159

is it?

**Comment by bbnp91** [comment]
I am also interested in a solution here, thanks.

**Comment by deepch** [comment]
the buffer in fact does not exist there is a queue of transmission must be instant.

ffplay vs mse or webrtc

ffplay -fflags nobuffer -rtsp_transport tcp 

<img width="1996" alt="Снимок экрана 2021-01-28 в 16 46 38" src="https://user-images.githubusercontent.com/7899955/106253639-cc41a480-6228-11eb-996d-374df379639d.png">
<img width="1879" alt="Снимок экрана 2021-01-28 в 16 43 20" src="https://user-images.githubusercontent.com/7899955/106253651-d1065880-6228-11eb-8870-95c9d15913b7.png">
