### ISSUE TITLE
how to solve the problem QQ browser run http://127.0.0.1:8083/  ?

### ISSUE THREAD

**Issue by chygfm** [deepch/RTSPtoWebRTC#67]
chrome run success, but QQ browser error:
 
![image](https://user-images.githubusercontent.com/62176381/106441550-248cd680-64b5-11eb-9622-9e7b9c22621d.png)

Uncaught DOMException: Failed to execute 'addTransceiver' on 'RTCPeerConnection': This operation is only supported in 'unified-plan'. 'unified-plan' will become the default behavior in the future, but it is currently experimental. To try it out, construct the RTCPeerConnection with sdpSemantics:'unified-plan' present in the RTCConfiguration argument.
    at Object.<anonymous> (http://127.0.0.1:8083/static/js/app.js?ver=2021-02-01%2017%3a33%3a37.6066189%20%2b0800%20CST%20m%3d%2b19081.153551801:46:12)
    at Function.each (http://127.0.0.1:8083/static/js/jquery-3.4.1.min.js:2:2777)
    at Object.success (http://127.0.0.1:8083/static/js/app.js?ver=2021-02-01%2017%3a33%3a37.6066189%20%2b0800%20CST%20m%3d%2b19081.153551801:45:9)
    at c (http://127.0.0.1:8083/static/js/jquery-3.4.1.min.js:2:27742)
    at Object.fireWith [as resolveWith] (http://127.0.0.1:8083/static/js/jquery-3.4.1.min.js:2:28487)
    at l (http://127.0.0.1:8083/static/js/jquery-3.4.1.min.js:2:78789)
    at XMLHttpRequest.<anonymous> (http://127.0.0.1:8083/static/js/jquery-3.4.1.min.js:2:81117)

Thanks!

**Comment by vdalex25** [comment]
in file app.js 
change config  to 
```javascript
let config = {
  iceServers: [{
    urls: ["stun:stun.l.google.com:19302"]
  }],
  sdpSemantics: "unified-plan"
};
```

**Comment by chygfm** [comment]
Thank you very much.It works but other 2 problems.

![image](https://user-images.githubusercontent.com/62176381/106539774-8db62d80-6539-11eb-9713-880d986f7371.png)
  "streams": {
    "H264_AAC": {
      "on_demand": true,
      "url": "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov"
    },

is the rtsp audio format not acc or other reason?

**Comment by deepch** [comment]
hi, WebRTC support only codec

```
const (
	// MimeTypeH264 H264 MIME type.
	// Note: Matching should be case insensitive.
	MimeTypeH264 = "video/h264"
	// MimeTypeOpus Opus MIME type
	// Note: Matching should be case insensitive.
	MimeTypeOpus = "audio/opus"
	// MimeTypeVP8 VP8 MIME type
	// Note: Matching should be case insensitive.
	MimeTypeVP8 = "video/vp8"
	// MimeTypeVP9 VP9 MIME type
	// Note: Matching should be case insensitive.
	MimeTypeVP9 = "video/vp9"
	// MimeTypeG722 G722 MIME type
	// Note: Matching should be case insensitive.
	MimeTypeG722 = "audio/G722"
	// MimeTypePCMU PCMU MIME type
	// Note: Matching should be case insensitive.
	MimeTypePCMU = "audio/PCMU"
	// MimeTypePCMA PCMA MIME type
	// Note: Matching should be case insensitive.
	MimeTypePCMA = "audio/PCMA"
)
```

if you need (aac) need transcoding audio format:

aac -> decode to PCM -> PCM encode (alaw, mulaw, or OPUS)


if you are using a IP camera then just select audio codec ALAW or MULAW it work

**Comment by chygfm** [comment]
Thanks!
