### ISSUE TITLE
Crash when proxying stream from rtsp-simple-server

### ISSUE THREAD

**Issue by blalor** [deepch/RTSPtoWebRTC#69]
I'm attempting to use `RTSPtoWebRTC` to view a webcam connected to a Raspberry Pi.  `RTSPtoWebRTC` crashes shortly after the browser connects.

On the pi:

1. download rtsp-simple-server binary: https://github.com/aler9/rtsp-simple-server/releases/tag/v0.14.0
2. configure to serve a stream from the attached camera; save as `rtsp-simple-server.yml`:

        # sets the verbosity of the program; available values are "warn", "info", "debug".
        logLevel: info

        # destinations of log messages; available values are "stdout", "file" and "syslog".
        logDestinations: [stdout]

        # listen IP. If provided, all listeners will listen on this specific IP.
        listenIP:

        # supported RTSP stream protocols.
        # UDP is the most performant, but can cause problems if there's a NAT between
        # server and clients, and doesn't support encryption.
        # TCP is the most versatile, and does support encryption.
        # The handshake is always performed with TCP.
        protocols: [udp, tcp]

        # encrypt handshake and TCP streams with TLS (RTSPS).
        # available values are "no", "strict", "optional".
        encryption: no

        # port of the TCP/RTSP listener. This is used only if encryption is "no" or "optional".
        rtspPort: 8554

        # port of the TCP/TLS/RTSPS listener. This is used only if encryption is "strict" or "optional".
        rtspsPort: 8555

        # port of the UDP/RTP listener. This is used only if "udp" is in protocols.
        rtpPort: 8000

        # port of the UDP/RTCP listener. This is used only if "udp" is in protocols.
        rtcpPort: 8001

        # authentication methods.
        authMethods: [basic, digest]

        # timeout of read operations.
        readTimeout: 10s

        # timeout of write operations.
        writeTimeout: 10s

        # number of read buffers.
        # a higher number allows a higher throughput,
        # a lower number allows to save RAM.
        readBufferCount: 512

        # enable a RTMP listener that allows to receive streams with RTMP.
        rtmpEnable: no

        # enable Prometheus-compatible metrics on port 9998.
        metrics: no

        # enable pprof on port 9999 to monitor performances.
        pprof: no

        # command to run when a client connects to the server.
        # this is terminated with SIGINT when a client disconnects from the server.
        # the server port is available in the RTSP_PORT variable.
        # the restart parameter allows to restart the command if it exits suddenly.
        runOnConnect:
        runOnConnectRestart: no

        # these settings are path-dependent.
        # it's possible to use regular expressions by using a tilde as prefix.
        # for example, "~^(test1|test2)$" will match both "test1" and "test2".
        # for example, "~^prefix" will match all paths that start with "prefix".
        # the settings under the path "all" are applied to all paths that do not match
        # another entry.
        paths:
          cam:
            runOnInit: ffmpeg -f v4l2 -i /dev/video0 -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
            runOnInitRestart: yes

3. verify the working stream with VLC: `vlc rtsp://pi.local:8554/cam`
4. configure `RTSPtoWebRTC`; save as `config.json`:

        {
          "server": {
            "http_port": ":8083"
          },
          "streams": {
            "octopi": {
              "on_demand": true,
              "url": "rtsp://pi.local:8554/cam"
            }
          }
        }

5. start `RTSPtoWebRTC`
6. point browser to http://localhost:8083
7. `RTSPtoWebRTC` will crash:

        [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

        [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
         - using env:   export GIN_MODE=release
         - using code:  gin.SetMode(gin.ReleaseMode)

        2021/02/04 08:48:38 Server Start Awaiting Signal
        [GIN-debug] Loaded HTML Templates (3):
            -
            - index.tmpl
            - player.tmpl

        [GIN-debug] GET    /                         --> main.HTTPAPIServerIndex (3 handlers)
        [GIN-debug] GET    /stream/player/:uuid      --> main.HTTPAPIServerStreamPlayer (3 handlers)
        [GIN-debug] POST   /stream/receiver/:uuid    --> main.HTTPAPIServerStreamWebRTC (3 handlers)
        [GIN-debug] GET    /stream/codec/:uuid       --> main.HTTPAPIServerStreamCodec (3 handlers)
        [GIN-debug] GET    /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
        [GIN-debug] HEAD   /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
        [GIN-debug] Listening and serving HTTP on :8083
        [GIN] 2021/02/04 - 08:48:42 | 200 |    1.732673ms |       127.0.0.1 | GET      "/stream/player/octopi"
        [GIN] 2021/02/04 - 08:48:42 | 304 |     627.788µs |       127.0.0.1 | GET      "/static/js/jquery-3.4.1.min.js"
        [GIN] 2021/02/04 - 08:48:42 | 304 |     646.768µs |       127.0.0.1 | GET      "/static/js/bootstrap.min.js"
        [GIN] 2021/02/04 - 08:48:42 | 304 |     254.599µs |       127.0.0.1 | GET      "/static/js/adapter-latest.js"
        [GIN] 2021/02/04 - 08:48:42 | 200 |   26.789544ms |       127.0.0.1 | GET      "/static/js/app.js?ver=2021-02-04%2008%3a48%3a42.375925%20-0500%20EST%20m%3d%2b4.352515692"
        2021/02/04 08:48:42 Stream Try Connect octopi
        [GIN] 2021/02/04 - 08:48:47 | 200 |  5.242178087s |       127.0.0.1 | GET      "/stream/codec/octopi"
        2021/02/04 08:48:53 Stream Codec Not Found
        [GIN] 2021/02/04 - 08:48:53 | 200 |  5.263643956s |       127.0.0.1 | POST     "/stream/receiver/octopi"
        2021/02/04 08:48:54 Stream Exit Rtsp Disconnect
        2021/02/04 08:48:54 Stream Exit On Demand No Viewer
        panic: runtime error: slice bounds out of range [:438] with capacity 436

        goroutine 53 [running]:
        github.com/deepch/vdk/codec/h264parser.SplitNALUs(0xc000534010, 0x1b8, 0x1b8, 0x2efffff, 0xc0000a8b68, 0x101a91e, 0x2d29a00)
            /Users/blalor/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210115152623-8d167fd1c067/codec/h264parser/parser.go:230 +0x6bb
        github.com/deepch/vdk/format/rtspv2.(*RTSPClient).RTPDemuxer(0xc0000fe000, 0xc00009da00, 0xc000534004, 0x1c4, 0x1c4, 0x1c4)
            /Users/blalor/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210115152623-8d167fd1c067/format/rtspv2/client.go:525 +0x208
        github.com/deepch/vdk/format/rtspv2.(*RTSPClient).startStream(0xc0000fe000)
            /Users/blalor/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210115152623-8d167fd1c067/format/rtspv2/client.go:265 +0x678
        created by github.com/deepch/vdk/format/rtspv2.Dial
            /Users/blalor/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210115152623-8d167fd1c067/format/rtspv2/client.go:198 +0x7de

**Comment by deepch** [comment]
corrupted stream need access to source.

If you have the ability to give me access to your stream, I could fix it quickly and efficiently.

share you RTSP stream https://en.wikipedia.org/wiki/Port_forwarding and please give me a link.

**Comment by blalor** [comment]
Email inbound. 😀

**Comment by deepch** [comment]
`    Stream #0:0: Video: mpeg4 (Simple Profile), yuv420p, 800x600 [SAR 1:1 DAR 4:3], 20 tbr, 90k tbn, 20 tbc
`
mpeg4 - old codec not supported WebRTC
try change codec to h264

**Comment by blalor** [comment]
That worked!  I changed the `runOnInit` line to

    ffmpeg -f v4l2 -i /dev/video0 -c:v h264_omx -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH

Thanks!  Would it be possible to get some diagnostic output from RTSPtoWebRTC to help users configure their streams correctly?

**Comment by deepch** [comment]
RTSPtoWebRTC - work only h264 

ffprobe -rtsp_transport tcp rtsp://YOU_STREAM:8554/cam

my cant is that I did not display in the log that the codec is not supported, I will correct it.
