### ISSUE TITLE
Multiple client do not work and it does not work in firefox.

### ISSUE THREAD

**Issue by ducbinh-ux** [deepch/RTSPtoWebRTC#7]
Thank you for thank you for great work. I run multiple client (Google chrome) when new window opened, old window disconnect and do not show video. I receive error in firefox InvalidSessionDescriptionError: Answer tried to set recv when offer did not set send. Please help me.

**Comment by deepch** [comment]
This is just an example, it is not correct. Describe what you would like to achieve?

**Comment by ducbinh-ux** [comment]
Dear deepch. Thank you for your answer. I am sorry for my english. I would like one rtsp can view by multiple client (web browser - one to many), and multiple rtsp can display.

**Comment by deepch** [comment]
I start to work creating a working example.

**Comment by deepch** [comment]
https://github.com/deepch/RTSPtoWSMP4f

**Comment by deepch** [comment]
actual?

**Comment by deepch** [comment]
please test new version.
