### ISSUE TITLE
separate stream logic and webserver

### ISSUE THREAD

**Issue by adambrakhane** [deepch/RTSPtoWebRTC#74]
I'd like to pull the stream conversion code into a new project. To do that, I'm going to need to strip out the web server functionality and replace those endpoints with a GO API instead. Are you guys interested in restructuring this project at all so that the stream functionality is its own module and can be pulled into projects without the API?

Here are a few options:
1) You guys separate the functionality into modules and I pull the bits I need.
2) We agree on some style & layout decisions, I make the changes myself, then make a PR. The only thing I would need from you guys would be design direction up front and for you to test your web functions at the end (I'm not going to be using or testing that part).
3) You're not interested in the change and I'll just copy out the bits I need.

Let me know if you're interested in working together!

**Comment by deepch** [comment]
Good day.

We can make you any project for your needs for a reasonable payment.

**Comment by adambrakhane** [comment]
Oh, I can do the work myself. I was just wondering if you guys would be interested in me contributing to your repo or not with my improvements.

**Comment by deepch** [comment]
We will be very glad for any help.
