### ISSUE TITLE
Load testing RTSPtoWebRTC

### ISSUE THREAD

**Issue by bbnp91** [deepch/RTSPtoWebRTC#76]
Hi, 

What is the best method for load testing this project. 
I have RTSPtoWebRTC running on a cloud VM, and I want to simulate multiple clients connecting to it to check stability/server capacity. 

Any ideas?

Thanks

**Comment by deepch** [comment]
HI,

This is not a full-fledged project, this is a scientific manual for its creation;) in fact, an example of how it can work.
What do you need it for?

**Comment by bbnp91** [comment]
Well it is a great project :)
I am streaming audio to a RTSP server, and I need to allow clients to subscribe to that stream on mobile clients. 
Latency and integration is an issue with the mobile frameworks available, VLC etc. So I am trying using WebRTC into a mobile browser. 

Audio stream is 64kb/s opus, and there are likely to be over 1000 clients, but I can manage that across multiple instances..

**Comment by deepch** [comment]
This is not a good solution. Since you will need a lot of udp ports.
The best solution is this  HLS - but there will be a delay, unfortunately, but you can make it optimal. I will soon make an example for such an implementation.

RTSPtoHLS
