### ISSUE TITLE
WritePacket WebRTC Codec Not Supported

### ISSUE THREAD

**Issue by PittYao** [deepch/RTSPtoWebRTC#78]
### videoSrc is rtsp H.264
- The screen appears after opening ，But blocked 。
- The screen will appear every time you open it, but then it's blocked 
-  And Console ：

> 2021/03/19 16:22:14 WritePacket WebRTC Codec Not Supported
2021/03/19 16:22:17 Client Not Send ACK (probably the browser is minimized) or tab not active Close client
2021/03/19 16:22:19 Client Not Send ACK (probably the browser is minimized) or tab not active Close client
2021/03/19 16:22:26 Stream Exit On Demand No Viewer
2021/03/19 16:22:26 Stream Exit On Demand No Viewer

![image](https://user-images.githubusercontent.com/26101917/111759926-1cf48600-88d9-11eb-9b47-131fb57cd78d.png)

**Comment by deepch** [comment]
Prompt in chrome / firefox browser do you have the same error? If not, what browser do you use?

**Comment by PittYao** [comment]
> Prompt in chrome / firefox browser do you have the same error? If not, what browser do you use?

No error will be reported when using Google Firefox 。I use uos browser, but it doesn’t matter, I will use  chrome。Thank you。
