### ISSUE TITLE
web client close webrtc,server do not close rtsp 

### ISSUE THREAD

**Issue by cquliaoli** [deepch/RTSPtoWebRTC#82]
![webrtc](https://user-images.githubusercontent.com/9543666/113078508-d4589900-9205-11eb-8dca-0708309521a3.png)
client swith different camera and close page,server do not close rtsp channel when no viewer.server inbound does not decrease.what should I do to close rtsp when no viewer open webrtc from web ?please help me,thank you.

**Comment by deepch** [comment]
hi try

`
 "on_demand": false,
`
change  to
`
 "on_demand": true,
`

**Comment by danbao12138** [comment]
When one video stream is in on-demand mode, it have one viewer more than 20 seconds, and it would never be closed.
Adding one line of code in line 60 of this stream.go file can solve this problem.
`clientTest.Reset(20 * time.Second ) //add clientTest calculator reset`

**Comment by cquliaoli** [comment]
> When one video stream is in on-demand mode, it have one viewer more than 20 seconds, and it would never be closed.
> Adding one line of code in line 60 of this stream.go file can solve this problem.
> `clientTest.Reset(20 * time.Second ) //add clientTest calculator reset`

thanks
