### ISSUE TITLE
[Advice] dynamically adding and deleting RTSP sources

### ISSUE THREAD

**Issue by imamiao** [deepch/RTSPtoWebRTC#96]
A great project!
Do you have any plans to add HTTP API interface to this project. Dynamically adding or deleting RTSP source configuration through API. If you can add this function, it will be more perfect. 
Thank you very much!

**Comment by deepch** [comment]
look to https://github.com/deepch/RTSPtoWeb

**Comment by imamiao** [comment]
> look to https://github.com/deepch/RTSPtoWeb

Perfect!!!
Thank you very much!
